---
name: buildkite-agent

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: buildkite-agent
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: awscliv2
    release: awscli2
    properties: {}
  - name: buildkite-agent
    release: buildkite-agent
    properties:
      token: ((token))

variables: []

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 1.1.8
  url: git+https://github.com/cloudfoundry/bpm-release
- name: awscli2
  sha1: 6c2ca326d180f486ffe0b221381ccc466572971e
  stemcell:
    os: ubuntu-xenial
    version: "621.61"
  url: https://s3.amazonaws.com/awscli2-boshrelease/compiled-releases/awscli2/awscli2-1.0.1-ubuntu-xenial-621.61-20200405-113949-162297918-20200405113953.tgz
  version: 1.0.1
- name: buildkite-agent
  version: create  # TODO: update after first final release
  url: .           # TODO: update after first final release
  # sha1:            TODO: update after first final release
