---
processes:
- name: buildkite-agent
  executable: /var/vcap/packages/buildkite-agent/bin/buildkite-agent
  args:
  - start
  - --config
  - /var/vcap/jobs/buildkite-agent/config/buildkite-agent.cfg
  - --bootstrap-script
  - /var/vcap/jobs/buildkite-agent/bin/bootstrap.sh
  ephemeral_disk: true
  persistent_disk: false
  additional_volumes:
  - path: /var/vcap/packages
  - path: /var/vcap/jobs
  # env: {}
  # limits:
  #   memory: 1G
  #   open_files: 1024

# examples/docs at:
# - https://github.com/cloudfoundry/bpm-release/blob/master/jobs/test-server/templates/bpm.yml.erb
# - https://github.com/cloudfoundry/bpm-release/tree/master/docs
